# -*- coding: utf-8 -*-
"""
01_calculate_rdkit_mollogp.py

Purpose
-------
Calculate RDKit MolLogP values for the external platform-independent
logP comparator audit.

Input
-----
data/processed/Dataset_S42_external_predictor_input.csv

Outputs
-------
data/processed/Dataset_S42a_RDKit_MolLogP_values.csv
data/processed/Dataset_S42a_RDKit_MolLogP_report.txt

Important
---------
This script does NOT modify Dataset_S1_benchmark_dataset.csv.
It uses Dataset_S42_external_predictor_input.csv generated by:
    00_prepare_external_predictor_input.py

RDKit MolLogP is the Wildman-Crippen atom-based logP implementation
available in RDKit.
"""

from pathlib import Path
import platform
import pandas as pd
import numpy as np


# ---------------------------------------------------------------------
# Project paths
# ---------------------------------------------------------------------
# This script is expected to be saved in:
# coumarin-logp/scripts/01_calculate_rdkit_mollogp.py
# Therefore, project root is one level above /scripts.
PROJECT_DIR = Path(__file__).resolve().parents[1]

INPUT_FILE = PROJECT_DIR / "data" / "processed" / "Dataset_S42_external_predictor_input.csv"

OUT_VALUES = PROJECT_DIR / "data" / "processed" / "Dataset_S42a_RDKit_MolLogP_values.csv"
OUT_REPORT = PROJECT_DIR / "data" / "processed" / "Dataset_S42a_RDKit_MolLogP_report.txt"


def calculate_r2(y_true: pd.Series, y_pred: pd.Series) -> float:
    ss_res = float(((y_true - y_pred) ** 2).sum())
    ss_tot = float(((y_true - y_true.mean()) ** 2).sum())
    if ss_tot == 0:
        return float("nan")
    return 1.0 - ss_res / ss_tot


def main() -> None:
    # -----------------------------------------------------------------
    # Import RDKit
    # -----------------------------------------------------------------
    try:
        from rdkit import Chem
        from rdkit.Chem import Crippen
        from rdkit import rdBase
        rdkit_version = rdBase.rdkitVersion
    except ImportError as exc:
        raise SystemExit(
            "\nRDKit is not installed in this Python environment.\n\n"
            "Install it with:\n"
            "    conda install -c conda-forge rdkit\n\n"
            "Then run this script again.\n"
        ) from exc

    if not INPUT_FILE.exists():
        raise FileNotFoundError(f"Input file not found:\n{INPUT_FILE}")

    OUT_VALUES.parent.mkdir(parents=True, exist_ok=True)

    df = pd.read_csv(INPUT_FILE, encoding="utf-8-sig")

    required_columns = ["Compound_ID", "SMILES", "logP_exp", "N_count", "FM"]
    missing = [col for col in required_columns if col not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns in input file: {missing}")

    rows = []

    for _, row in df.iterrows():
        compound_id = row["Compound_ID"]
        smiles = row["SMILES"]

        mol = Chem.MolFromSmiles(smiles)

        if mol is None:
            rows.append(
                {
                    "Compound_ID": compound_id,
                    "SMILES": smiles,
                    "logP_exp": row["logP_exp"],
                    "N_count": row["N_count"],
                    "FM": row["FM"],
                    "RDKit_MolLogP": np.nan,
                    "delta_RDKit_MolLogP": np.nan,
                    "abs_delta_RDKit_MolLogP": np.nan,
                    "RDKit_status": "SMILES_PARSE_FAILED",
                }
            )
            continue

        rdkit_logp = float(Crippen.MolLogP(mol))
        logp_exp = float(row["logP_exp"])
        delta = logp_exp - rdkit_logp

        rows.append(
            {
                "Compound_ID": compound_id,
                "SMILES": smiles,
                "logP_exp": logp_exp,
                "N_count": int(row["N_count"]),
                "FM": row["FM"],
                "RDKit_MolLogP": rdkit_logp,
                "delta_RDKit_MolLogP": delta,
                "abs_delta_RDKit_MolLogP": abs(delta),
                "RDKit_status": "OK",
            }
        )

    out = pd.DataFrame(rows)
    out.to_csv(OUT_VALUES, index=False, encoding="utf-8")

    # -----------------------------------------------------------------
    # Performance summary
    # -----------------------------------------------------------------
    valid = out["RDKit_status"].eq("OK") & out["RDKit_MolLogP"].notna()

    if valid.sum() == 0:
        raise ValueError("No valid RDKit MolLogP values were calculated.")

    y_true = out.loc[valid, "logP_exp"].astype(float)
    y_pred = out.loc[valid, "RDKit_MolLogP"].astype(float)
    delta = out.loc[valid, "delta_RDKit_MolLogP"].astype(float)

    bias = float(delta.mean())
    mae = float(delta.abs().mean())
    rmse = float(np.sqrt(np.mean(delta ** 2)))
    r2 = calculate_r2(y_true, y_pred)
    overestimated_percent = float((delta < 0).mean() * 100)
    severe_abs_error_percent = float((delta.abs() >= 2.0).mean() * 100)

    polar_mask = valid & (out["logP_exp"].astype(float) <= 1.0)
    high_risk_mask = (
        valid
        & out["N_count"].astype(int).between(1, 3)
        & (out["logP_exp"].astype(float) < 1.5)
    )

    polar_bias = float(out.loc[polar_mask, "delta_RDKit_MolLogP"].mean())
    high_risk_bias = float(out.loc[high_risk_mask, "delta_RDKit_MolLogP"].mean())

    # -----------------------------------------------------------------
    # Report
    # -----------------------------------------------------------------
    report = []
    report.append("Dataset_S42a RDKit MolLogP calculation report")
    report.append("=" * 70)
    report.append("")
    report.append(f"Project directory: {PROJECT_DIR}")
    report.append(f"Input file: {INPUT_FILE}")
    report.append(f"Output values: {OUT_VALUES}")
    report.append(f"Output report: {OUT_REPORT}")
    report.append("")
    report.append("1. Software information")
    report.append("-" * 70)
    report.append(f"Python version: {platform.python_version()}")
    report.append(f"RDKit version: {rdkit_version}")
    report.append("")
    report.append("2. Calculation status")
    report.append("-" * 70)
    report.append(f"Total compounds: {len(out)}")
    report.append(f"Valid RDKit MolLogP values: {int(valid.sum())}")
    report.append(f"Failed compounds: {int((~valid).sum())}")
    report.append("")
    report.append("RDKit_status distribution:")
    for key, val in out["RDKit_status"].value_counts().items():
        report.append(f"  {key}: {int(val)}")
    report.append("")
    report.append("3. RDKit MolLogP performance summary")
    report.append("-" * 70)
    report.append(f"Bias: {bias:.3f}")
    report.append(f"MAE: {mae:.3f}")
    report.append(f"RMSE: {rmse:.3f}")
    report.append(f"R2: {r2:.3f}")
    report.append(f"Overestimated compounds: {overestimated_percent:.1f}%")
    report.append(f"Severe absolute error compounds: {severe_abs_error_percent:.1f}%")
    report.append(f"Polar logP <= 1.0 bias: {polar_bias:.3f}")
    report.append(f"N = 1-3 and logP < 1.5 bias: {high_risk_bias:.3f}")
    report.append("")
    report.append("4. Interpretation note")
    report.append("-" * 70)
    report.append(
        "RDKit MolLogP is included as a reproducible external comparator. "
        "It is not used to train, recalibrate, or replace any SwissADME-associated "
        "predictor. Its role is to test whether the observed prediction-error "
        "architecture is restricted to the SwissADME suite or also appears in "
        "a platform-independent atom-based logP implementation."
    )

    OUT_REPORT.write_text("\n".join(report), encoding="utf-8")

    print("\n".join(report))
    print("")
    print("SUCCESS: RDKit MolLogP calculation completed.")


if __name__ == "__main__":
    main()