# -*- coding: utf-8 -*-
"""
Generate and validate electron-density and electrostatic-potential cubes
for the three added FM2 DFT anchors using ORCA orca_plot.

Targets:
- CMR_GOLD_090
- CMR_GOLD_020
- CMR_GOLD_092

Required files per molecule:
- dft/molecules/<ID>/input/<ID>_sp.gbw
- dft/molecules/<ID>/input/<ID>_sp.densities
- dft/molecules/<ID>/geometry/<ID>_opt.xyz

Outputs per molecule:
- dft/molecules/<ID>/cube/<ID>_density.cube
- dft/molecules/<ID>/cube/<ID>_esp.cube
- dft/molecules/<ID>/cube/<ID>_sp.eldens.cube        if generated by ORCA
- dft/molecules/<ID>/cube/<ID>_sp.scfp.esp.cube      if generated by ORCA
- dft/molecules/<ID>/extracted_data/<ID>_cube_validation_report.txt
- dft/molecules/<ID>/extracted_data/<ID>_cube_validation_report.csv

Combined:
- data/processed/Dataset_S40_FM2_MEP_cube_validation_summary.csv
- data/processed/Dataset_S40_FM2_MEP_cube_generation_report.txt
"""

from pathlib import Path
import shutil
import subprocess
import time
import csv
import numpy as np
import pandas as pd


PROJECT = Path(r"D:\Makaleler\coumarin-logp-working-source")
ORCA_PLOT = Path(r"C:\orca\orca_plot.exe")

TARGET_IDS = ["CMR_GOLD_090", "CMR_GOLD_020", "CMR_GOLD_092"]

DATA_OUT = PROJECT / "data" / "processed"
DATA_OUT.mkdir(parents=True, exist_ok=True)

COMMON_MEP_MIN = -0.08
COMMON_MEP_MAX = 0.08
RHO_ISO = 0.004


def read_cube(path: Path):
    lines = path.read_text(errors="ignore").splitlines()

    natoms_line = lines[2].split()
    natoms = int(natoms_line[0])
    origin = np.array([float(natoms_line[1]), float(natoms_line[2]), float(natoms_line[3])])

    grid = []
    axes = []

    for i in range(3):
        parts = lines[3 + i].split()
        n = int(parts[0])
        vec = np.array([float(parts[1]), float(parts[2]), float(parts[3])])
        grid.append(n)
        axes.append(vec)

    atom_start = 6
    atom_end = atom_start + abs(natoms)

    data_tokens = []
    for line in lines[atom_end:]:
        data_tokens.extend(line.split())

    data = np.array([float(x) for x in data_tokens], dtype=float)
    expected = abs(grid[0] * grid[1] * grid[2])

    if data.size != expected:
        raise RuntimeError(
            f"{path.name}: cube data size mismatch. Expected {expected}, found {data.size}"
        )

    return {
        "path": path,
        "natoms": natoms,
        "origin": origin,
        "grid": tuple(grid),
        "axes": tuple(tuple(v) for v in axes),
        "flat": data,
    }


def run_orcaplot(stem: str, workdir: Path, sequence: str, log_path: Path, label: str):
    if not ORCA_PLOT.exists():
        raise FileNotFoundError(f"orca_plot bulunamadı: {ORCA_PLOT}")

    cmd = [str(ORCA_PLOT), f"{stem}.gbw", "-i"]

    print(f"\n=== {label} ===")
    print("Workdir:", workdir)
    print("Command:", " ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=str(workdir),
        input=sequence,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        timeout=3600,
    )

    log_path.write_text(result.stdout, encoding="utf-8", errors="ignore")

    print("Return code:", result.returncode)
    print("Log:", log_path)

    if result.returncode != 0:
        print("UYARI: orca_plot return code 0 değil. Log kontrol edilmeli.")

    return result.returncode


def assign_final_cubes(cid: str, cube_dir: Path):
    cubes = list(cube_dir.rglob("*.cube"))

    density_candidates = [
        c for c in cubes
        if any(k in c.name.lower() for k in ["eldens", "density", "dens"])
    ]

    esp_candidates = [
        c for c in cubes
        if any(k in c.name.lower() for k in ["esp", "potential", "elpot", "scfp"])
    ]

    density_final = cube_dir / f"{cid}_density.cube"
    esp_final = cube_dir / f"{cid}_esp.cube"

    if density_candidates:
        src = sorted(density_candidates, key=lambda p: p.stat().st_size, reverse=True)[0]
        shutil.copy2(src, density_final)
        print(f"Density cube final: {src.name} -> {density_final.name}")
    else:
        print(f"UYARI: {cid} density cube otomatik tanınamadı.")

    if esp_candidates:
        src = sorted(esp_candidates, key=lambda p: p.stat().st_size, reverse=True)[0]
        shutil.copy2(src, esp_final)
        print(f"ESP cube final    : {src.name} -> {esp_final.name}")
    else:
        print(f"UYARI: {cid} ESP cube otomatik tanınamadı.")

    return density_final, esp_final


def validate_cubes(cid: str, density_cube: Path, esp_cube: Path, data_dir: Path):
    if not density_cube.exists():
        raise FileNotFoundError(f"Density cube yok: {density_cube}")
    if not esp_cube.exists():
        raise FileNotFoundError(f"ESP cube yok: {esp_cube}")

    dens = read_cube(density_cube)
    esp = read_cube(esp_cube)

    same_grid = dens["grid"] == esp["grid"]
    same_origin = np.allclose(dens["origin"], esp["origin"])
    same_axes = dens["axes"] == esp["axes"]
    same_natoms = dens["natoms"] == esp["natoms"]

    rho = dens["flat"]
    vesp = esp["flat"]

    shell_mask = (rho > RHO_ISO * 0.90) & (rho < RHO_ISO * 1.10)
    shell_count = int(shell_mask.sum())

    shell_esp_min = float(np.min(vesp[shell_mask])) if shell_count else None
    shell_esp_max = float(np.max(vesp[shell_mask])) if shell_count else None
    shell_esp_mean = float(np.mean(vesp[shell_mask])) if shell_count else None

    report = {
        "Molecule_ID": cid,
        "Density_cube": str(density_cube),
        "ESP_cube": str(esp_cube),
        "Same_grid": same_grid,
        "Same_origin": same_origin,
        "Same_axes": same_axes,
        "Same_natoms": same_natoms,
        "Grid": str(dens["grid"]),
        "Natoms": dens["natoms"],
        "Density_min": float(np.min(rho)),
        "Density_max": float(np.max(rho)),
        "Density_mean": float(np.mean(rho)),
        "ESP_min": float(np.min(vesp)),
        "ESP_max": float(np.max(vesp)),
        "ESP_mean": float(np.mean(vesp)),
        "Isosurface_density_au": RHO_ISO,
        "Near_isosurface_shell_points": shell_count,
        "ESP_min_near_rho_0p004": shell_esp_min,
        "ESP_max_near_rho_0p004": shell_esp_max,
        "ESP_mean_near_rho_0p004": shell_esp_mean,
        "Common_MEP_scale_min_au": COMMON_MEP_MIN,
        "Common_MEP_scale_max_au": COMMON_MEP_MAX,
        "ESP_values_outside_common_scale_total": int(((vesp < COMMON_MEP_MIN) | (vesp > COMMON_MEP_MAX)).sum()),
    }

    txt_path = data_dir / f"{cid}_cube_validation_report.txt"
    csv_path = data_dir / f"{cid}_cube_validation_report.csv"

    with txt_path.open("w", encoding="utf-8") as f:
        f.write(f"{cid} cube validation report\n")
        f.write("=" * 72 + "\n\n")
        for k, v in report.items():
            f.write(f"{k}: {v}\n")

    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Field", "Value"])
        for k, v in report.items():
            writer.writerow([k, v])

    report["Validation_txt"] = str(txt_path)
    report["Validation_csv"] = str(csv_path)

    return report


def prepare_files(cid: str):
    mol_dir = PROJECT / "dft" / "molecules" / cid
    input_dir = mol_dir / "input"
    geom_dir = mol_dir / "geometry"
    cube_dir = mol_dir / "cube"
    data_dir = mol_dir / "extracted_data"

    cube_dir.mkdir(parents=True, exist_ok=True)
    data_dir.mkdir(parents=True, exist_ok=True)

    stem = f"{cid}_sp"

    gbw_input = input_dir / f"{stem}.gbw"
    densities_input = input_dir / f"{stem}.densities"
    xyz_input = geom_dir / f"{cid}_opt.xyz"

    if not gbw_input.exists():
        raise FileNotFoundError(f"{cid}: GBW bulunamadı: {gbw_input}")
    if not densities_input.exists():
        raise FileNotFoundError(f"{cid}: densities container bulunamadı: {densities_input}")
    if not xyz_input.exists():
        raise FileNotFoundError(f"{cid}: optimized XYZ bulunamadı: {xyz_input}")

    gbw_cube = cube_dir / f"{stem}.gbw"
    dens_cube = cube_dir / f"{stem}.densities"
    xyz_cube = cube_dir / f"{stem}.xyz"

    shutil.copy2(gbw_input, gbw_cube)
    shutil.copy2(densities_input, dens_cube)
    shutil.copy2(xyz_input, xyz_cube)

    # Clean old generated cubes only for this molecule
    for c in cube_dir.glob("*.cube"):
        c.unlink()

    return mol_dir, cube_dir, data_dir, stem


def generate_for_molecule(cid: str):
    print("\n" + "=" * 80)
    print(f"Generating cubes for {cid}")
    print("=" * 80)

    mol_dir, cube_dir, data_dir, stem = prepare_files(cid)

    density_log = data_dir / f"{cid}_orcaplot_density.log"
    esp_log = data_dir / f"{cid}_orcaplot_esp.log"

    density_sequence = "\n".join([
        "1",
        "2",
        "y",
        "5",
        "7",
        "11",
        "12",
        ""
    ])

    esp_sequence = "\n".join([
        "1",
        "43",
        f"input\\{stem}.scfp",
        "5",
        "7",
        "11",
        "12",
        ""
    ])

    run_orcaplot(stem, cube_dir, density_sequence, density_log, f"{cid} electron density cube")
    time.sleep(2)

    run_orcaplot(stem, cube_dir, esp_sequence, esp_log, f"{cid} electrostatic potential cube")
    time.sleep(2)

    print("\nGenerated cube files:")
    for c in cube_dir.glob("*.cube"):
        print(f"  {c.name} | {c.stat().st_size} bytes")

    density_final, esp_final = assign_final_cubes(cid, cube_dir)

    validation = validate_cubes(cid, density_final, esp_final, data_dir)

    validation["Density_log"] = str(density_log)
    validation["ESP_log"] = str(esp_log)
    validation["Cube_dir"] = str(cube_dir)

    print("\nValidation:")
    for k in ["Same_grid", "Same_origin", "Same_axes", "Same_natoms", "Grid", "Near_isosurface_shell_points"]:
        print(f"  {k}: {validation[k]}")

    return validation


def main():
    all_reports = []

    for cid in TARGET_IDS:
        report = generate_for_molecule(cid)
        all_reports.append(report)

    summary = pd.DataFrame(all_reports)

    out_csv = DATA_OUT / "Dataset_S40_FM2_MEP_cube_validation_summary.csv"
    out_txt = DATA_OUT / "Dataset_S40_FM2_MEP_cube_generation_report.txt"

    summary.to_csv(out_csv, index=False, encoding="utf-8-sig")

    with out_txt.open("w", encoding="utf-8") as f:
        f.write("FM2 MEP cube generation and validation report\n")
        f.write("=" * 80 + "\n\n")
        f.write(summary.to_string(index=False))
        f.write("\n")

    print("\n" + "=" * 80)
    print("FM2 MEP cube generation completed.")
    print(f"Summary CSV: {out_csv}")
    print(f"Report TXT : {out_txt}")
    print("\nSummary:")
    show_cols = [
        "Molecule_ID",
        "Same_grid",
        "Same_origin",
        "Same_axes",
        "Same_natoms",
        "Grid",
        "Near_isosurface_shell_points",
        "ESP_min_near_rho_0p004",
        "ESP_max_near_rho_0p004",
    ]
    print(summary[show_cols].to_string(index=False))

    if summary[["Same_grid", "Same_origin", "Same_axes", "Same_natoms"]].all(axis=None):
        print("\nAll generated density/ESP cube pairs are grid-compatible.")
    else:
        print("\nWARNING: At least one density/ESP cube pair has grid mismatch.")


if __name__ == "__main__":
    main()